# https://taskfile.dev

version: '3'

vars:
  NAME: gosimple

tasks:


  build:
    desc: build go
    cmds:
      - env GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o ./dist/main main.go
      - chmod +x ./dist/main
      - cd ./dist && zip main.zip main
    sources:
      - ./*.go
      - main/*.go
      - Taskfile.yml
    generates:
      - ../dist/main
    silent: true

  deploy:
    desc: Deploy only Lambda function
    deps: [build]
    cmds:
      - aws lambda update-function-code --function-name  {{.NAME}} --zip-file fileb://./dist/main.zip

  deploy-ssm:
    desc: Deploy only lambda
    deps: [build]
    vars:
      FN:      
        sh: aws ssm get-parameter --name "simplefunction" --query "Parameter.Value" --output text
    cmds:
      - aws lambda update-function-code --function-name  {{.FN}} --zip-file fileb://./dist/main.zip

  invoke:
    desc: Call lambda
    cmds:
      - aws lambda invoke --function-name {{.NAME}} --payload fileb://testdata/event.json testdata/lambda.out
      - cat testdata/lambda.out

