service: state-machine-image-processor
frameworkVersion: '>=1.28.0 <2.0.0'

plugins:
  - serverless-step-functions
provider:
  name: aws
  runtime: go1.x
  memorySize: 128
  timeout: 5
  stage: dev 
  region: us-east-1
  endpointType: regional
  # iamRoleStatements:
  #   - Effect: Allow 
  #     Action: 
  #       - states:StartExecution
  #     Resource: arn:aws:states:us-east-1:132172135366:stateMachine:HelloStepFunc

# package:
#   exclude:
#     - ./**
#   include:
#     - ./build/**

# functions:
#   stateInvoke:
#     handler: build/stateInvoke
#     environment:
#       STATE_MACHINE_ARN: ${self:resources.Outputs.HelloStepFunc.Value}
#     description: "This lambda invokes a state machine"

stepFunctions:
  stateMachines:
    ImageProcessor:
        name: ImageProcessor
        definition:
          Comment: ImageProcessor
          StartAt: GetFileType
          States:
            GetFileType:
              Comment: GetFileType
              Type: Pass
              Next: CheckFileType
            CheckFileType:
              Comment: CheckFileType
              Type: Pass
              End: true
# resources:
#   Outputs:
#     HelloStepFunc:
#       Description: The ARN of the example state machine
#       Value:
#         Ref: HelloStepFunc
