// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: transaction/cart.proto

package transaction

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CartItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemUuid      string                 `protobuf:"bytes,1,opt,name=item_uuid,json=item_id,proto3" json:"item_uuid,omitempty"`
	Quantity      uint32                 `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	ItemPrice     uint32                 `protobuf:"varint,3,opt,name=item_price,proto3" json:"item_price,omitempty"`
	Taxable       bool                   `protobuf:"varint,4,opt,name=taxable,proto3" json:"taxable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartItem) Reset() {
	*x = CartItem{}
	mi := &file_transaction_cart_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartItem) ProtoMessage() {}

func (x *CartItem) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_cart_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartItem.ProtoReflect.Descriptor instead.
func (*CartItem) Descriptor() ([]byte, []int) {
	return file_transaction_cart_proto_rawDescGZIP(), []int{0}
}

func (x *CartItem) GetItemUuid() string {
	if x != nil {
		return x.ItemUuid
	}
	return ""
}

func (x *CartItem) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CartItem) GetItemPrice() uint32 {
	if x != nil {
		return x.ItemPrice
	}
	return 0
}

func (x *CartItem) GetTaxable() bool {
	if x != nil {
		return x.Taxable
	}
	return false
}

type Cart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CartUuid      string                 `protobuf:"bytes,1,opt,name=cart_uuid,proto3" json:"cart_uuid,omitempty"`
	Items         []*CartItem            `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cart) Reset() {
	*x = Cart{}
	mi := &file_transaction_cart_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cart) ProtoMessage() {}

func (x *Cart) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_cart_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cart.ProtoReflect.Descriptor instead.
func (*Cart) Descriptor() ([]byte, []int) {
	return file_transaction_cart_proto_rawDescGZIP(), []int{1}
}

func (x *Cart) GetCartUuid() string {
	if x != nil {
		return x.CartUuid
	}
	return ""
}

func (x *Cart) GetItems() []*CartItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_transaction_cart_proto protoreflect.FileDescriptor

const file_transaction_cart_proto_rawDesc = "" +
	"\n" +
	"\x16transaction/cart.proto\x12\vtransaction\"|\n" +
	"\bCartItem\x12\x1a\n" +
	"\titem_uuid\x18\x01 \x01(\tR\aitem_id\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\rR\bquantity\x12\x1e\n" +
	"\n" +
	"item_price\x18\x03 \x01(\rR\n" +
	"item_price\x12\x18\n" +
	"\ataxable\x18\x04 \x01(\bR\ataxable\"Q\n" +
	"\x04Cart\x12\x1c\n" +
	"\tcart_uuid\x18\x01 \x01(\tR\tcart_uuid\x12+\n" +
	"\x05items\x18\x02 \x03(\v2\x15.transaction.CartItemR\x05itemsB\x19Z\x17protogen/go/transactionb\x06proto3"

var (
	file_transaction_cart_proto_rawDescOnce sync.Once
	file_transaction_cart_proto_rawDescData []byte
)

func file_transaction_cart_proto_rawDescGZIP() []byte {
	file_transaction_cart_proto_rawDescOnce.Do(func() {
		file_transaction_cart_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transaction_cart_proto_rawDesc), len(file_transaction_cart_proto_rawDesc)))
	})
	return file_transaction_cart_proto_rawDescData
}

var file_transaction_cart_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_transaction_cart_proto_goTypes = []any{
	(*CartItem)(nil), // 0: transaction.CartItem
	(*Cart)(nil),     // 1: transaction.Cart
}
var file_transaction_cart_proto_depIdxs = []int32{
	0, // 0: transaction.Cart.items:type_name -> transaction.CartItem
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_transaction_cart_proto_init() }
func file_transaction_cart_proto_init() {
	if File_transaction_cart_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transaction_cart_proto_rawDesc), len(file_transaction_cart_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_transaction_cart_proto_goTypes,
		DependencyIndexes: file_transaction_cart_proto_depIdxs,
		MessageInfos:      file_transaction_cart_proto_msgTypes,
	}.Build()
	File_transaction_cart_proto = out.File
	file_transaction_cart_proto_goTypes = nil
	file_transaction_cart_proto_depIdxs = nil
}
