version: '3'

tasks:
  build:
    dir: './hello'
    cmds:
      - mkdir -p ./protogen
      - protoc --go_out=./protogen --go_opt=paths=source_relative ./*.proto
  run:
    dir: '.'
    deps: [build]
    cmds:
      - go run main.go
  execute:
    dir: '.'
    cmds:
      - go run main.go