url: https://ce6d-69-115-187-42.ngrok.io
apps:
  app1:
    clientID: "1-2-3-4"
    clientSecret: "secret"
    issuer: https://ce6d-69-115-187-42.ngrok.io
    redirectURIs: [http://localhost:8081/callback]