// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: resiliency/type/resiliency.proto

package resiliency

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResiliencyRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MinDelaySecond int32                  `protobuf:"varint,1,opt,name=min_delay_second,proto3" json:"min_delay_second,omitempty"`
	MaxDelaySecond int32                  `protobuf:"varint,2,opt,name=max_delay_second,proto3" json:"max_delay_second,omitempty"`
	StatusCodes    []uint32               `protobuf:"varint,3,rep,packed,name=status_codes,proto3" json:"status_codes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResiliencyRequest) Reset() {
	*x = ResiliencyRequest{}
	mi := &file_resiliency_type_resiliency_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResiliencyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResiliencyRequest) ProtoMessage() {}

func (x *ResiliencyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resiliency_type_resiliency_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResiliencyRequest.ProtoReflect.Descriptor instead.
func (*ResiliencyRequest) Descriptor() ([]byte, []int) {
	return file_resiliency_type_resiliency_proto_rawDescGZIP(), []int{0}
}

func (x *ResiliencyRequest) GetMinDelaySecond() int32 {
	if x != nil {
		return x.MinDelaySecond
	}
	return 0
}

func (x *ResiliencyRequest) GetMaxDelaySecond() int32 {
	if x != nil {
		return x.MaxDelaySecond
	}
	return 0
}

func (x *ResiliencyRequest) GetStatusCodes() []uint32 {
	if x != nil {
		return x.StatusCodes
	}
	return nil
}

type ResiliencyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      string                 `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	StatusCode    uint32                 `protobuf:"varint,2,opt,name=status_code,proto3" json:"status_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResiliencyResponse) Reset() {
	*x = ResiliencyResponse{}
	mi := &file_resiliency_type_resiliency_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResiliencyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResiliencyResponse) ProtoMessage() {}

func (x *ResiliencyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_resiliency_type_resiliency_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResiliencyResponse.ProtoReflect.Descriptor instead.
func (*ResiliencyResponse) Descriptor() ([]byte, []int) {
	return file_resiliency_type_resiliency_proto_rawDescGZIP(), []int{1}
}

func (x *ResiliencyResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

func (x *ResiliencyResponse) GetStatusCode() uint32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

var File_resiliency_type_resiliency_proto protoreflect.FileDescriptor

const file_resiliency_type_resiliency_proto_rawDesc = "" +
	"\n" +
	" resiliency/type/resiliency.proto\x12\n" +
	"resiliency\x1a.protoc-gen-openapiv2/options/annotations.proto\"\x84\x02\n" +
	"\x11ResiliencyRequest\x12V\n" +
	"\x10min_delay_second\x18\x01 \x01(\x05B*\x92A'2\x18Minimum delay in secondsJ\x012\xa2\x02\aintegerR\x10min_delay_second\x12V\n" +
	"\x10max_delay_second\x18\x02 \x01(\x05B*\x92A'2\x18Maximum delay in secondsJ\x017\xa2\x02\aintegerR\x10max_delay_second\x12?\n" +
	"\fstatus_codes\x18\x03 \x03(\rB\x1b\x92A\x182\x16Status codes to returnR\fstatus_codes\"s\n" +
	"\x12ResiliencyResponse\x12)\n" +
	"\bresponse\x18\x01 \x01(\tB\r\x92A\n" +
	"2\bResponseR\bresponse\x122\n" +
	"\vstatus_code\x18\x02 \x01(\rB\x10\x92A\r2\vStatus codeR\vstatus_codeB\x18Z\x16protogen/go/resiliencyb\x06proto3"

var (
	file_resiliency_type_resiliency_proto_rawDescOnce sync.Once
	file_resiliency_type_resiliency_proto_rawDescData []byte
)

func file_resiliency_type_resiliency_proto_rawDescGZIP() []byte {
	file_resiliency_type_resiliency_proto_rawDescOnce.Do(func() {
		file_resiliency_type_resiliency_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_resiliency_type_resiliency_proto_rawDesc), len(file_resiliency_type_resiliency_proto_rawDesc)))
	})
	return file_resiliency_type_resiliency_proto_rawDescData
}

var file_resiliency_type_resiliency_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_resiliency_type_resiliency_proto_goTypes = []any{
	(*ResiliencyRequest)(nil),  // 0: resiliency.ResiliencyRequest
	(*ResiliencyResponse)(nil), // 1: resiliency.ResiliencyResponse
}
var file_resiliency_type_resiliency_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_resiliency_type_resiliency_proto_init() }
func file_resiliency_type_resiliency_proto_init() {
	if File_resiliency_type_resiliency_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_resiliency_type_resiliency_proto_rawDesc), len(file_resiliency_type_resiliency_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_resiliency_type_resiliency_proto_goTypes,
		DependencyIndexes: file_resiliency_type_resiliency_proto_depIdxs,
		MessageInfos:      file_resiliency_type_resiliency_proto_msgTypes,
	}.Build()
	File_resiliency_type_resiliency_proto = out.File
	file_resiliency_type_resiliency_proto_goTypes = nil
	file_resiliency_type_resiliency_proto_depIdxs = nil
}
