// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: resiliency/service.proto

package resiliency

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_resiliency_service_proto protoreflect.FileDescriptor

const file_resiliency_service_proto_rawDesc = "" +
	"\n" +
	"\x18resiliency/service.proto\x12\n" +
	"resiliency\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a resiliency/type/resiliency.proto2\xc6\b\n" +
	"\x11ResiliencyService\x12|\n" +
	"\rGetResiliency\x12\x1d.resiliency.ResiliencyRequest\x1a\x1e.resiliency.ResiliencyResponse\",\x82\xd3\xe4\x93\x02&:\x01*\"!/api/resiliency/v1/metadata/unary\x12\xac\x02\n" +
	"\x13GetResiliencyStream\x12\x1d.resiliency.ResiliencyRequest\x1a\x1e.resiliency.ResiliencyResponse\"\xd3\x01\x92A\x98\x01\x12\x1fSummary for GetResiliencyStream\x1a#Description for GetResiliencyStreamJ'\n" +
	"\x03200\x12 \n" +
	"\x1eSamplen response, 200 when ...J'\n" +
	"\x03400\x12 \n" +
	"\x1eSamplen response, 400 when ...\x82\xd3\xe4\x93\x021:\x01*\",/api/resiliency/v1/metadata/server_streaming0\x01\x12\xaf\x02\n" +
	"\x14SendResiliencyStream\x12\x1d.resiliency.ResiliencyRequest\x1a\x1e.resiliency.ResiliencyResponse\"\xd5\x01\x92A\x9a\x01\x12 Summary for SendResiliencyStream\x1a$Description for SendResiliencyStreamJ'\n" +
	"\x03200\x12 \n" +
	"\x1eSamplen response, 200 when ...J'\n" +
	"\x03400\x12 \n" +
	"\x1eSamplen response, 400 when ...\x82\xd3\xe4\x93\x021:\x01*\",/api/resiliency/v1/metadata/client_streaming(\x01\x12\xd1\x02\n" +
	"\x1dBidirectionalResiliencyStream\x12\x1d.resiliency.ResiliencyRequest\x1a\x1e.resiliency.ResiliencyResponse\"\xec\x01\x92A\xaa\x01\x12(Summary for BidirectionalResiliencyStrea\x1a,Description for BidirectionalResiliencyStreaJ'\n" +
	"\x03200\x12 \n" +
	"\x1eSamplen response, 200 when ...J'\n" +
	"\x03400\x12 \n" +
	"\x1eSamplen response, 400 when ...\x82\xd3\xe4\x93\x028:\x01*\"3/api/resiliency/v1/metadata/bidirectional_streaming(\x010\x01Bc\x92AH\x12!\n" +
	"\x18Course - Protobuf & gRPC2\x051.0.0\x1a\x0elocalhost:8081*\x01\x01:\x10application/jsonZ\x16protogen/go/resiliencyb\x06proto3"

var file_resiliency_service_proto_goTypes = []any{
	(*ResiliencyRequest)(nil),  // 0: resiliency.ResiliencyRequest
	(*ResiliencyResponse)(nil), // 1: resiliency.ResiliencyResponse
}
var file_resiliency_service_proto_depIdxs = []int32{
	0, // 0: resiliency.ResiliencyService.GetResiliency:input_type -> resiliency.ResiliencyRequest
	0, // 1: resiliency.ResiliencyService.GetResiliencyStream:input_type -> resiliency.ResiliencyRequest
	0, // 2: resiliency.ResiliencyService.SendResiliencyStream:input_type -> resiliency.ResiliencyRequest
	0, // 3: resiliency.ResiliencyService.BidirectionalResiliencyStream:input_type -> resiliency.ResiliencyRequest
	1, // 4: resiliency.ResiliencyService.GetResiliency:output_type -> resiliency.ResiliencyResponse
	1, // 5: resiliency.ResiliencyService.GetResiliencyStream:output_type -> resiliency.ResiliencyResponse
	1, // 6: resiliency.ResiliencyService.SendResiliencyStream:output_type -> resiliency.ResiliencyResponse
	1, // 7: resiliency.ResiliencyService.BidirectionalResiliencyStream:output_type -> resiliency.ResiliencyResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_resiliency_service_proto_init() }
func file_resiliency_service_proto_init() {
	if File_resiliency_service_proto != nil {
		return
	}
	file_resiliency_type_resiliency_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_resiliency_service_proto_rawDesc), len(file_resiliency_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_resiliency_service_proto_goTypes,
		DependencyIndexes: file_resiliency_service_proto_depIdxs,
	}.Build()
	File_resiliency_service_proto = out.File
	file_resiliency_service_proto_goTypes = nil
	file_resiliency_service_proto_depIdxs = nil
}
