
Vagrant.configure(2) do |config|

  config.vm.box = "skade/rasperry-pi-devbox"
  config.vm.box_version = "1.0"

  config.vm.network "forwarded_port", guest: 3000, host: 3000

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network "private_network", ip: "192.168.33.10"

 
  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
     # Customize the amount of memory on the VM:
  #   vb.memory = "16384"
  end
 

  config.vm.synced_folder "/Users/romelcampbell/go", "/go", :nfs => { :mount_options => ["dmode=777","fmode=777"] }
 

  config.vm.provision :shell, path: "bootstrap.sh"

  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"


end
