// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: bank/type/account.proto

package bank

import (
	date "google.golang.org/genproto/googleapis/type/date"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CurrentBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountNumber string                 `protobuf:"bytes,1,opt,name=account_number,proto3" json:"account_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrentBalanceRequest) Reset() {
	*x = CurrentBalanceRequest{}
	mi := &file_bank_type_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrentBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentBalanceRequest) ProtoMessage() {}

func (x *CurrentBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bank_type_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentBalanceRequest.ProtoReflect.Descriptor instead.
func (*CurrentBalanceRequest) Descriptor() ([]byte, []int) {
	return file_bank_type_account_proto_rawDescGZIP(), []int{0}
}

func (x *CurrentBalanceRequest) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

type CurrentBalanceResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CurrentBalance float64                `protobuf:"fixed64,1,opt,name=current_balance,proto3" json:"current_balance,omitempty"`
	CurrentDate    *date.Date             `protobuf:"bytes,2,opt,name=current_date,proto3" json:"current_date,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CurrentBalanceResponse) Reset() {
	*x = CurrentBalanceResponse{}
	mi := &file_bank_type_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrentBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentBalanceResponse) ProtoMessage() {}

func (x *CurrentBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bank_type_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentBalanceResponse.ProtoReflect.Descriptor instead.
func (*CurrentBalanceResponse) Descriptor() ([]byte, []int) {
	return file_bank_type_account_proto_rawDescGZIP(), []int{1}
}

func (x *CurrentBalanceResponse) GetCurrentBalance() float64 {
	if x != nil {
		return x.CurrentBalance
	}
	return 0
}

func (x *CurrentBalanceResponse) GetCurrentDate() *date.Date {
	if x != nil {
		return x.CurrentDate
	}
	return nil
}

type CreateAccountRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	AccountName          string                 `protobuf:"bytes,1,opt,name=account_name,proto3" json:"account_name,omitempty"`
	Currency             string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	InitialDepositAmount float64                `protobuf:"fixed64,3,opt,name=initial_deposit_amount,proto3" json:"initial_deposit_amount,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CreateAccountRequest) Reset() {
	*x = CreateAccountRequest{}
	mi := &file_bank_type_account_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountRequest) ProtoMessage() {}

func (x *CreateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bank_type_account_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return file_bank_type_account_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAccountRequest) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

func (x *CreateAccountRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateAccountRequest) GetInitialDepositAmount() float64 {
	if x != nil {
		return x.InitialDepositAmount
	}
	return 0
}

type CreateAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountUuid   string                 `protobuf:"bytes,1,opt,name=account_uuid,proto3" json:"account_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountResponse) Reset() {
	*x = CreateAccountResponse{}
	mi := &file_bank_type_account_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountResponse) ProtoMessage() {}

func (x *CreateAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bank_type_account_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountResponse.ProtoReflect.Descriptor instead.
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return file_bank_type_account_proto_rawDescGZIP(), []int{3}
}

func (x *CreateAccountResponse) GetAccountUuid() string {
	if x != nil {
		return x.AccountUuid
	}
	return ""
}

var File_bank_type_account_proto protoreflect.FileDescriptor

const file_bank_type_account_proto_rawDesc = "" +
	"\n" +
	"\x17bank/type/account.proto\x12\x04bank\x1a\x16google/type/date.proto\"?\n" +
	"\x15CurrentBalanceRequest\x12&\n" +
	"\x0eaccount_number\x18\x01 \x01(\tR\x0eaccount_number\"y\n" +
	"\x16CurrentBalanceResponse\x12(\n" +
	"\x0fcurrent_balance\x18\x01 \x01(\x01R\x0fcurrent_balance\x125\n" +
	"\fcurrent_date\x18\x02 \x01(\v2\x11.google.type.DateR\fcurrent_date\"\x8e\x01\n" +
	"\x14CreateAccountRequest\x12\"\n" +
	"\faccount_name\x18\x01 \x01(\tR\faccount_name\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\x126\n" +
	"\x16initial_deposit_amount\x18\x03 \x01(\x01R\x16initial_deposit_amount\";\n" +
	"\x15CreateAccountResponse\x12\"\n" +
	"\faccount_uuid\x18\x01 \x01(\tR\faccount_uuidB\x12Z\x10protogen/go/bankb\x06proto3"

var (
	file_bank_type_account_proto_rawDescOnce sync.Once
	file_bank_type_account_proto_rawDescData []byte
)

func file_bank_type_account_proto_rawDescGZIP() []byte {
	file_bank_type_account_proto_rawDescOnce.Do(func() {
		file_bank_type_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bank_type_account_proto_rawDesc), len(file_bank_type_account_proto_rawDesc)))
	})
	return file_bank_type_account_proto_rawDescData
}

var file_bank_type_account_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_bank_type_account_proto_goTypes = []any{
	(*CurrentBalanceRequest)(nil),  // 0: bank.CurrentBalanceRequest
	(*CurrentBalanceResponse)(nil), // 1: bank.CurrentBalanceResponse
	(*CreateAccountRequest)(nil),   // 2: bank.CreateAccountRequest
	(*CreateAccountResponse)(nil),  // 3: bank.CreateAccountResponse
	(*date.Date)(nil),              // 4: google.type.Date
}
var file_bank_type_account_proto_depIdxs = []int32{
	4, // 0: bank.CurrentBalanceResponse.current_date:type_name -> google.type.Date
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_bank_type_account_proto_init() }
func file_bank_type_account_proto_init() {
	if File_bank_type_account_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bank_type_account_proto_rawDesc), len(file_bank_type_account_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bank_type_account_proto_goTypes,
		DependencyIndexes: file_bank_type_account_proto_depIdxs,
		MessageInfos:      file_bank_type_account_proto_msgTypes,
	}.Build()
	File_bank_type_account_proto = out.File
	file_bank_type_account_proto_goTypes = nil
	file_bank_type_account_proto_depIdxs = nil
}
