// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: bank/service.proto

package bank

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_bank_service_proto protoreflect.FileDescriptor

const file_bank_service_proto_rawDesc = "" +
	"\n" +
	"\x12bank/service.proto\x12\x04bank\x1a\x17bank/type/account.proto\x1a\x18bank/type/exchange.proto\x1a\x1bbank/type/transaction.proto\x1a\x18bank/type/transfer.proto2\xeb\x03\n" +
	"\vBankService\x12P\n" +
	"\x11GetCurrentBalance\x12\x1b.bank.CurrentBalanceRequest\x1a\x1c.bank.CurrentBalanceResponse\"\x00\x12O\n" +
	"\x12FetchExchangeRates\x12\x19.bank.ExchangeRateRequest\x1a\x1a.bank.ExchangeRateResponse\"\x000\x01\x12H\n" +
	"\x15SummarizeTransactions\x12\x11.bank.Transaction\x1a\x18.bank.TransactionSummary\"\x00(\x01\x12G\n" +
	"\x10TransferMultiple\x12\x15.bank.TransferRequest\x1a\x16.bank.TransferResponse\"\x00(\x010\x01\x12Z\n" +
	"\x1bGetCurrentBalanceWithStatus\x12\x1b.bank.CurrentBalanceRequest\x1a\x1c.bank.CurrentBalanceResponse\"\x00\x12J\n" +
	"\rCreateAccount\x12\x1a.bank.CreateAccountRequest\x1a\x1b.bank.CreateAccountResponse\"\x00B\x12Z\x10protogen/go/bankb\x06proto3"

var file_bank_service_proto_goTypes = []any{
	(*CurrentBalanceRequest)(nil),  // 0: bank.CurrentBalanceRequest
	(*ExchangeRateRequest)(nil),    // 1: bank.ExchangeRateRequest
	(*Transaction)(nil),            // 2: bank.Transaction
	(*TransferRequest)(nil),        // 3: bank.TransferRequest
	(*CreateAccountRequest)(nil),   // 4: bank.CreateAccountRequest
	(*CurrentBalanceResponse)(nil), // 5: bank.CurrentBalanceResponse
	(*ExchangeRateResponse)(nil),   // 6: bank.ExchangeRateResponse
	(*TransactionSummary)(nil),     // 7: bank.TransactionSummary
	(*TransferResponse)(nil),       // 8: bank.TransferResponse
	(*CreateAccountResponse)(nil),  // 9: bank.CreateAccountResponse
}
var file_bank_service_proto_depIdxs = []int32{
	0, // 0: bank.BankService.GetCurrentBalance:input_type -> bank.CurrentBalanceRequest
	1, // 1: bank.BankService.FetchExchangeRates:input_type -> bank.ExchangeRateRequest
	2, // 2: bank.BankService.SummarizeTransactions:input_type -> bank.Transaction
	3, // 3: bank.BankService.TransferMultiple:input_type -> bank.TransferRequest
	0, // 4: bank.BankService.GetCurrentBalanceWithStatus:input_type -> bank.CurrentBalanceRequest
	4, // 5: bank.BankService.CreateAccount:input_type -> bank.CreateAccountRequest
	5, // 6: bank.BankService.GetCurrentBalance:output_type -> bank.CurrentBalanceResponse
	6, // 7: bank.BankService.FetchExchangeRates:output_type -> bank.ExchangeRateResponse
	7, // 8: bank.BankService.SummarizeTransactions:output_type -> bank.TransactionSummary
	8, // 9: bank.BankService.TransferMultiple:output_type -> bank.TransferResponse
	5, // 10: bank.BankService.GetCurrentBalanceWithStatus:output_type -> bank.CurrentBalanceResponse
	9, // 11: bank.BankService.CreateAccount:output_type -> bank.CreateAccountResponse
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bank_service_proto_init() }
func file_bank_service_proto_init() {
	if File_bank_service_proto != nil {
		return
	}
	file_bank_type_account_proto_init()
	file_bank_type_exchange_proto_init()
	file_bank_type_transaction_proto_init()
	file_bank_type_transfer_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bank_service_proto_rawDesc), len(file_bank_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bank_service_proto_goTypes,
		DependencyIndexes: file_bank_service_proto_depIdxs,
	}.Build()
	File_bank_service_proto = out.File
	file_bank_service_proto_goTypes = nil
	file_bank_service_proto_depIdxs = nil
}
