// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: bank/type/transaction.proto

package bank

import (
	date "google.golang.org/genproto/googleapis/type/date"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransactionType int32

const (
	TransactionType_TRANSACTION_TYPE_UNSPECIFIED TransactionType = 0
	TransactionType_TRANSACTION_TYPE_DEPOSIT     TransactionType = 1
	TransactionType_TRANSACTION_TYPE_WITHDRAWAL  TransactionType = 2
)

// Enum value maps for TransactionType.
var (
	TransactionType_name = map[int32]string{
		0: "TRANSACTION_TYPE_UNSPECIFIED",
		1: "TRANSACTION_TYPE_DEPOSIT",
		2: "TRANSACTION_TYPE_WITHDRAWAL",
	}
	TransactionType_value = map[string]int32{
		"TRANSACTION_TYPE_UNSPECIFIED": 0,
		"TRANSACTION_TYPE_DEPOSIT":     1,
		"TRANSACTION_TYPE_WITHDRAWAL":  2,
	}
)

func (x TransactionType) Enum() *TransactionType {
	p := new(TransactionType)
	*p = x
	return p
}

func (x TransactionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionType) Descriptor() protoreflect.EnumDescriptor {
	return file_bank_type_transaction_proto_enumTypes[0].Descriptor()
}

func (TransactionType) Type() protoreflect.EnumType {
	return &file_bank_type_transaction_proto_enumTypes[0]
}

func (x TransactionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionType.Descriptor instead.
func (TransactionType) EnumDescriptor() ([]byte, []int) {
	return file_bank_type_transaction_proto_rawDescGZIP(), []int{0}
}

type Transaction struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AccountNumber   string                 `protobuf:"bytes,1,opt,name=account_number,proto3" json:"account_number,omitempty"`
	TransactionType TransactionType        `protobuf:"varint,2,opt,name=transaction_type,proto3,enum=bank.TransactionType" json:"transaction_type,omitempty"`
	Amount          float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Timestamp       *date.Date             `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_bank_type_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_bank_type_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_bank_type_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *Transaction) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *Transaction) GetTransactionType() TransactionType {
	if x != nil {
		return x.TransactionType
	}
	return TransactionType_TRANSACTION_TYPE_UNSPECIFIED
}

func (x *Transaction) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Transaction) GetTimestamp() *date.Date {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type TransactionSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountNumber string                 `protobuf:"bytes,1,opt,name=account_number,proto3" json:"account_number,omitempty"`
	Balance       float64                `protobuf:"fixed64,2,opt,name=balance,proto3" json:"balance,omitempty"`
	Transactions  []*Transaction         `protobuf:"bytes,3,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionSummary) Reset() {
	*x = TransactionSummary{}
	mi := &file_bank_type_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionSummary) ProtoMessage() {}

func (x *TransactionSummary) ProtoReflect() protoreflect.Message {
	mi := &file_bank_type_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionSummary.ProtoReflect.Descriptor instead.
func (*TransactionSummary) Descriptor() ([]byte, []int) {
	return file_bank_type_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *TransactionSummary) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *TransactionSummary) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *TransactionSummary) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

var File_bank_type_transaction_proto protoreflect.FileDescriptor

const file_bank_type_transaction_proto_rawDesc = "" +
	"\n" +
	"\x1bbank/type/transaction.proto\x12\x04bank\x1a\x16google/type/date.proto\"\xc1\x01\n" +
	"\vTransaction\x12&\n" +
	"\x0eaccount_number\x18\x01 \x01(\tR\x0eaccount_number\x12A\n" +
	"\x10transaction_type\x18\x02 \x01(\x0e2\x15.bank.TransactionTypeR\x10transaction_type\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12/\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x11.google.type.DateR\ttimestamp\"\x8d\x01\n" +
	"\x12TransactionSummary\x12&\n" +
	"\x0eaccount_number\x18\x01 \x01(\tR\x0eaccount_number\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x01R\abalance\x125\n" +
	"\ftransactions\x18\x03 \x03(\v2\x11.bank.TransactionR\ftransactions*r\n" +
	"\x0fTransactionType\x12 \n" +
	"\x1cTRANSACTION_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18TRANSACTION_TYPE_DEPOSIT\x10\x01\x12\x1f\n" +
	"\x1bTRANSACTION_TYPE_WITHDRAWAL\x10\x02B\x12Z\x10protogen/go/bankb\x06proto3"

var (
	file_bank_type_transaction_proto_rawDescOnce sync.Once
	file_bank_type_transaction_proto_rawDescData []byte
)

func file_bank_type_transaction_proto_rawDescGZIP() []byte {
	file_bank_type_transaction_proto_rawDescOnce.Do(func() {
		file_bank_type_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bank_type_transaction_proto_rawDesc), len(file_bank_type_transaction_proto_rawDesc)))
	})
	return file_bank_type_transaction_proto_rawDescData
}

var file_bank_type_transaction_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_bank_type_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_bank_type_transaction_proto_goTypes = []any{
	(TransactionType)(0),       // 0: bank.TransactionType
	(*Transaction)(nil),        // 1: bank.Transaction
	(*TransactionSummary)(nil), // 2: bank.TransactionSummary
	(*date.Date)(nil),          // 3: google.type.Date
}
var file_bank_type_transaction_proto_depIdxs = []int32{
	0, // 0: bank.Transaction.transaction_type:type_name -> bank.TransactionType
	3, // 1: bank.Transaction.timestamp:type_name -> google.type.Date
	1, // 2: bank.TransactionSummary.transactions:type_name -> bank.Transaction
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_bank_type_transaction_proto_init() }
func file_bank_type_transaction_proto_init() {
	if File_bank_type_transaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bank_type_transaction_proto_rawDesc), len(file_bank_type_transaction_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bank_type_transaction_proto_goTypes,
		DependencyIndexes: file_bank_type_transaction_proto_depIdxs,
		EnumInfos:         file_bank_type_transaction_proto_enumTypes,
		MessageInfos:      file_bank_type_transaction_proto_msgTypes,
	}.Build()
	File_bank_type_transaction_proto = out.File
	file_bank_type_transaction_proto_goTypes = nil
	file_bank_type_transaction_proto_depIdxs = nil
}
