service: iotbutton
frameworkVersion: '>=1.28.0 <2.0.0'

provider:
  name: aws
  runtime: go1.x
  iamRoleStatements:
    - Effect: Allow 
      Action: 
        - SNS:Publish
      Resource: "*"
package:
  exclude:
    - ./**
  include:
    - ./build/**

functions:
  buttonClick:
    handler: build/click