// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Hobby struct {
	ID          string `json:"id"`
	Title       string `json:"title"`
	Description string `json:"description"`
}

type NewPost struct {
	Comment string `json:"comment"`
	UserID  string `json:"userId"`
}

type NewUser struct {
	Name       string `json:"name"`
	Age        int    `json:"age"`
	Profession string `json:"profession"`
}

type User struct {
	ID         string `json:"id"`
	Name       string `json:"name"`
	Age        int    `json:"age"`
	Profession string `json:"profession"`
}
