service: sls-cicd
frameworkVersion: '>=1.28.0 <2.0.0'

provider:
  name: aws
  runtime: go1.x
  stage: dev
  region: us-east-1
  memorySize: 128
  timeout: 3

package:
  exclude:
    - ./**
  include:
    - ./build/**

functions:
  logger:
    handler: build/logger
    events:
      - http:
          path: message
          method: get