    # 1. Update config values (localhost --> mongo and localhost --> redis) in config.development.json
    # 2. Set APP_ENV environment variable to proper value in Dockerfile-redis (default is "development")
    #    export APP_ENV=development
    # 3. Run docker-compose build
    # 4. Run docker-compose up
    # 5. Live long and prosper
    
version: "2"
 
services:
    developmentt:
      container_name: development
      build: 
        context: .
        dockerfile: .docker/Dockerfile-development
      ports:
        - "8080"
      volumes:
        - .:/var/www/development
      working_dir: /var/www/development
      networks:
        - development-network
    redis:
      container_name: redis
      build: 
        context: .
        dockerfile: .docker/docker-redis.dockerfile
      ports:
        - "6380:6379"
      env_file:
        - ./.docker/env/app.${APP_ENV}.env
      networks:
        - development-network
    mysql:
      container_name: mysql
      build: 
        context: .
        dockerfile: .docker/docker-mysql.dockerfile
      ports:
        - "3307:3306"
      env_file:
        - ./.docker/env/app.${APP_ENV}.env
      networks:
        - development-network
        
networks:
    development-network:
      driver: bridge
