    # 1. Update config values (localhost --> mongo and localhost --> redis) in config.development.json
    # 2. Set APP_ENV environment variable to proper value in Dockerfile-redis (default is "development")
    #    export APP_ENV=development
    # 3. Run docker-compose build
    # 4. Run docker-compose up
    # 5. Live long and prosper
    
version: "2"


networks:
    go-network:
      driver: bridge
 
services:
    development:
      container_name: development
      build: 
        context: .
        dockerfile: .docker/development.dockerfile
      ports:
        - "3000:3000"
      volumes:
        - .:/go/src/app
      working_dir: /go/src/app
      env_file:
        - ./db/mysql/config/env.conf
      networks:
        - go-network
    redis:
      container_name: redis
      build: 
        context: .
        dockerfile: .docker/docker-redis.dockerfile
      ports:
        - "6379:6379"
      env_file:
        - ./db/redis/config/env.conf
      networks:
        - go-network
    mysql:
      container_name: mysql
      build: 
        context: .
        dockerfile: .docker/docker-mysql.dockerfile
      ports:
        - "3306:3306"
      volumes:
        - ./db/mysql/data:/var/lib/mysql:rw
        - ./scripts:/scripts:rw
      env_file:
        - ./db/mysql/config/env.conf
      command: "/scripts/mysql.sh"
      networks:
        - go-network
  
        