version: '3'

vars:
  BIN_FILENAME:  my-ggrpc-server

tasks:

  build_bin:
    dir: '.'
    cmds:
      - go mod tidy
      - go build -o ./bin/{{.BIN_FILENAME}} ./cmd

  build:
    cmds:
      - task build_bin

  # docker-compose-up:
  #   cmds:
  #     - docker-compose down
  #     - docker-compose up -d

  dbreset:
    cmds:
      # - task docker-compose-up
      # - sleep 20
      - celeritas migrate reset

  run:
    cmds:
      - task build_bin
      # - task dbreset
      - ./bin/{{.BIN_FILENAME}}

  execute:
    cmds:
      # - task dbreset
      - ./bin/{{.BIN_FILENAME}}

