apiVersion: v1
kind: Pod
metadata: 
  name: kuard-tls
spec:
  containers:
    - image: gcr.io/kuar-demo/kuard-arm:1
      name: kuard-tls
      imagePullPolicy: Always
      volumeMounts:
        - name:  tls-certs
          mountPath:  "/tls"
          readOnly: true
  imagePullSecrets:
    - name: my-image-pull-secret
  volumes:
    - name: tls-certs
      secret:
        secretName: kuard-tls
