apiVersion: v1
kind: Pod
metadata: 
  name: kuard
spec:
  volumes:
    - name: "kuard-data"
      persistentVolumeClaim:
        claimName: database        
  containers:
    - image: gcr.io/kuar-demo/kuard-arm:1
      name: kuard
      volumeMounts:
        - mountPath: "/data"
          name: "kuard-data"
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
