// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "adder": Application Media Types
//
// Command:
// $ goagen
// --design=github.com/GOCODE/goa-adder/design
// --out=$(GOPATH)/src/github.com/GOCODE/goa-adder
// --version=v1.2.0-dirty

package client
