# Docker compose for multi-org-ca-1
#DEV_MODE_NET
version: '2'

networks:
  airline:

services:
  
  # Postgres
  postgresql:
    container_name: postgresql
    image: postgres:9.5
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      
    working_dir: $HOME
    volumes:
    # Folder with genesis block
    #- ${PWD}:/etc/postgresql/9.5/main
    # orig - $PWD/explorer/bins:/home/vagrant/bins
    - ${PWD}/explorer/bins:/home/vagrant/bins
    - /var/run/postgresql:/var/run/postgresql
    ports:
      - 5432:5432
    networks:
      - airline
  
  explorer:
    container_name: explorer
    image: acloudfan/hlf-explorer
    environment:
      - DATABASE_PASSWORD=postgres
      - DATABASE_HOST=postgresql
    volumes:
      # - ${PWD}/explorer/bins:/home/vagrant/bins
      # - ${PWD}/../crypto:/vagrant/network/crypto
      - ${PWD}/explorer/bins:/home/vagrant/bins
      - ${PWD}/../crypto:/vagrant/network/crypto
      - /var/run/postgresql:/var/run/postgresql
    ports:
      - 8080:8080
    depends_on: 
      - postgresql
    networks:
      - airline