version: "2"

services:
    development:
      container_name: development
      build: 
        context: .
        dockerfile: .docker/development.dockerfile
      ports:
        - "3000:3000"
      volumes:
        - .:/go/src/github.com/GOCODE/graphQL
      working_dir: /go/src/github.com/GOCODE/graphQL
