// Code generated by protoc-gen-go. DO NOT EDIT.
// source: calculator/calculatorpb/calculator.proto

package calculatorpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Nums struct {
	FirstNum             float32  `protobuf:"fixed32,1,opt,name=first_num,json=firstNum,proto3" json:"first_num,omitempty"`
	SecondNum            float32  `protobuf:"fixed32,2,opt,name=second_num,json=secondNum,proto3" json:"second_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Nums) Reset()         { *m = Nums{} }
func (m *Nums) String() string { return proto.CompactTextString(m) }
func (*Nums) ProtoMessage()    {}
func (*Nums) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{0}
}

func (m *Nums) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Nums.Unmarshal(m, b)
}
func (m *Nums) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Nums.Marshal(b, m, deterministic)
}
func (m *Nums) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Nums.Merge(m, src)
}
func (m *Nums) XXX_Size() int {
	return xxx_messageInfo_Nums.Size(m)
}
func (m *Nums) XXX_DiscardUnknown() {
	xxx_messageInfo_Nums.DiscardUnknown(m)
}

var xxx_messageInfo_Nums proto.InternalMessageInfo

func (m *Nums) GetFirstNum() float32 {
	if m != nil {
		return m.FirstNum
	}
	return 0
}

func (m *Nums) GetSecondNum() float32 {
	if m != nil {
		return m.SecondNum
	}
	return 0
}

type SumRequest struct {
	Nums                 *Nums    `protobuf:"bytes,1,opt,name=nums,proto3" json:"nums,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SumRequest) Reset()         { *m = SumRequest{} }
func (m *SumRequest) String() string { return proto.CompactTextString(m) }
func (*SumRequest) ProtoMessage()    {}
func (*SumRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{1}
}

func (m *SumRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SumRequest.Unmarshal(m, b)
}
func (m *SumRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SumRequest.Marshal(b, m, deterministic)
}
func (m *SumRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SumRequest.Merge(m, src)
}
func (m *SumRequest) XXX_Size() int {
	return xxx_messageInfo_SumRequest.Size(m)
}
func (m *SumRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SumRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SumRequest proto.InternalMessageInfo

func (m *SumRequest) GetNums() *Nums {
	if m != nil {
		return m.Nums
	}
	return nil
}

type SumResponse struct {
	Total                float32  `protobuf:"fixed32,1,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SumResponse) Reset()         { *m = SumResponse{} }
func (m *SumResponse) String() string { return proto.CompactTextString(m) }
func (*SumResponse) ProtoMessage()    {}
func (*SumResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{2}
}

func (m *SumResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SumResponse.Unmarshal(m, b)
}
func (m *SumResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SumResponse.Marshal(b, m, deterministic)
}
func (m *SumResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SumResponse.Merge(m, src)
}
func (m *SumResponse) XXX_Size() int {
	return xxx_messageInfo_SumResponse.Size(m)
}
func (m *SumResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SumResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SumResponse proto.InternalMessageInfo

func (m *SumResponse) GetTotal() float32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type PrimeNumbersRequest struct {
	Number               int64    `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrimeNumbersRequest) Reset()         { *m = PrimeNumbersRequest{} }
func (m *PrimeNumbersRequest) String() string { return proto.CompactTextString(m) }
func (*PrimeNumbersRequest) ProtoMessage()    {}
func (*PrimeNumbersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{3}
}

func (m *PrimeNumbersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimeNumbersRequest.Unmarshal(m, b)
}
func (m *PrimeNumbersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimeNumbersRequest.Marshal(b, m, deterministic)
}
func (m *PrimeNumbersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimeNumbersRequest.Merge(m, src)
}
func (m *PrimeNumbersRequest) XXX_Size() int {
	return xxx_messageInfo_PrimeNumbersRequest.Size(m)
}
func (m *PrimeNumbersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimeNumbersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PrimeNumbersRequest proto.InternalMessageInfo

func (m *PrimeNumbersRequest) GetNumber() int64 {
	if m != nil {
		return m.Number
	}
	return 0
}

type PrimeNumbersResponse struct {
	Result               int64    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrimeNumbersResponse) Reset()         { *m = PrimeNumbersResponse{} }
func (m *PrimeNumbersResponse) String() string { return proto.CompactTextString(m) }
func (*PrimeNumbersResponse) ProtoMessage()    {}
func (*PrimeNumbersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{4}
}

func (m *PrimeNumbersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimeNumbersResponse.Unmarshal(m, b)
}
func (m *PrimeNumbersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimeNumbersResponse.Marshal(b, m, deterministic)
}
func (m *PrimeNumbersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimeNumbersResponse.Merge(m, src)
}
func (m *PrimeNumbersResponse) XXX_Size() int {
	return xxx_messageInfo_PrimeNumbersResponse.Size(m)
}
func (m *PrimeNumbersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimeNumbersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PrimeNumbersResponse proto.InternalMessageInfo

func (m *PrimeNumbersResponse) GetResult() int64 {
	if m != nil {
		return m.Result
	}
	return 0
}

func init() {
	proto.RegisterType((*Nums)(nil), "calculator.Nums")
	proto.RegisterType((*SumRequest)(nil), "calculator.SumRequest")
	proto.RegisterType((*SumResponse)(nil), "calculator.SumResponse")
	proto.RegisterType((*PrimeNumbersRequest)(nil), "calculator.PrimeNumbersRequest")
	proto.RegisterType((*PrimeNumbersResponse)(nil), "calculator.PrimeNumbersResponse")
}

func init() {
	proto.RegisterFile("calculator/calculatorpb/calculator.proto", fileDescriptor_7f42938f8c8365cf)
}

var fileDescriptor_7f42938f8c8365cf = []byte{
	// 277 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x4d, 0x5b, 0x8b, 0x9d, 0x16, 0xd1, 0xb5, 0x44, 0xa9, 0x88, 0x65, 0xf5, 0xd0, 0x8b,
	0x51, 0xe2, 0xc5, 0x73, 0xbd, 0x07, 0x49, 0xf0, 0xe2, 0x45, 0x92, 0xb8, 0x42, 0x20, 0xbb, 0x1b,
	0x77, 0x77, 0xfc, 0x45, 0xfe, 0x50, 0x71, 0x92, 0x98, 0x15, 0xf5, 0xb6, 0xef, 0xcd, 0xdb, 0xf9,
	0x66, 0x18, 0xd8, 0x94, 0x79, 0x5d, 0x62, 0x9d, 0x3b, 0x6d, 0xae, 0x87, 0x67, 0x53, 0x78, 0x22,
	0x6a, 0x8c, 0x76, 0x9a, 0xc1, 0xe0, 0xf0, 0x2d, 0x4c, 0x12, 0x94, 0x96, 0x9d, 0xc2, 0xec, 0xb5,
	0x32, 0xd6, 0x3d, 0x2b, 0x94, 0x27, 0xc1, 0x3a, 0xd8, 0x8c, 0xd2, 0x3d, 0x32, 0x12, 0x94, 0xec,
	0x0c, 0xc0, 0x8a, 0x52, 0xab, 0x17, 0xaa, 0x8e, 0xa8, 0x3a, 0x6b, 0x9d, 0x04, 0x25, 0x8f, 0x01,
	0x32, 0x94, 0xa9, 0x78, 0x43, 0x61, 0x1d, 0xbb, 0x84, 0x89, 0x42, 0x69, 0xa9, 0xc9, 0x3c, 0x3e,
	0x88, 0x3c, 0xfc, 0x17, 0x29, 0xa5, 0x2a, 0xbf, 0x80, 0x39, 0xfd, 0xb1, 0x8d, 0x56, 0x56, 0xb0,
	0x25, 0xec, 0x3a, 0xed, 0xf2, 0xba, 0x43, 0xb7, 0x82, 0x5f, 0xc1, 0xd1, 0x83, 0xa9, 0xa4, 0x48,
	0x50, 0x16, 0xc2, 0xd8, 0x9e, 0x10, 0xc2, 0x54, 0x91, 0x43, 0xe9, 0x71, 0xda, 0x29, 0x1e, 0xc1,
	0xf2, 0x67, 0xbc, 0x6b, 0x1e, 0xc2, 0xd4, 0x08, 0x8b, 0xb5, 0xeb, 0xf3, 0xad, 0x8a, 0x3f, 0x02,
	0x38, 0xbc, 0xff, 0x9e, 0x2e, 0x13, 0xe6, 0xbd, 0x2a, 0x05, 0xbb, 0x83, 0x71, 0x86, 0x92, 0x85,
	0xfe, 0xe0, 0xc3, 0x7a, 0xab, 0xe3, 0x5f, 0x7e, 0x4b, 0xe1, 0x3b, 0xec, 0x11, 0x16, 0x3e, 0x9f,
	0x9d, 0xfb, 0xd1, 0x3f, 0x16, 0x59, 0xad, 0xff, 0x0f, 0xf4, 0x4d, 0x6f, 0x82, 0xed, 0xfe, 0xd3,
	0xc2, 0xbf, 0x67, 0x31, 0xa5, 0x2b, 0xde, 0x7e, 0x06, 0x00, 0x00, 0xff, 0xff, 0x7d, 0x19, 0x7e,
	0x59, 0xf1, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CalculatorServiceClient is the client API for CalculatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CalculatorServiceClient interface {
	// Unary
	Sum(ctx context.Context, in *SumRequest, opts ...grpc.CallOption) (*SumResponse, error)
	PrimeNumbers(ctx context.Context, in *PrimeNumbersRequest, opts ...grpc.CallOption) (CalculatorService_PrimeNumbersClient, error)
}

type calculatorServiceClient struct {
	cc *grpc.ClientConn
}

func NewCalculatorServiceClient(cc *grpc.ClientConn) CalculatorServiceClient {
	return &calculatorServiceClient{cc}
}

func (c *calculatorServiceClient) Sum(ctx context.Context, in *SumRequest, opts ...grpc.CallOption) (*SumResponse, error) {
	out := new(SumResponse)
	err := c.cc.Invoke(ctx, "/calculator.CalculatorService/Sum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calculatorServiceClient) PrimeNumbers(ctx context.Context, in *PrimeNumbersRequest, opts ...grpc.CallOption) (CalculatorService_PrimeNumbersClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CalculatorService_serviceDesc.Streams[0], "/calculator.CalculatorService/PrimeNumbers", opts...)
	if err != nil {
		return nil, err
	}
	x := &calculatorServicePrimeNumbersClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CalculatorService_PrimeNumbersClient interface {
	Recv() (*PrimeNumbersResponse, error)
	grpc.ClientStream
}

type calculatorServicePrimeNumbersClient struct {
	grpc.ClientStream
}

func (x *calculatorServicePrimeNumbersClient) Recv() (*PrimeNumbersResponse, error) {
	m := new(PrimeNumbersResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CalculatorServiceServer is the server API for CalculatorService service.
type CalculatorServiceServer interface {
	// Unary
	Sum(context.Context, *SumRequest) (*SumResponse, error)
	PrimeNumbers(*PrimeNumbersRequest, CalculatorService_PrimeNumbersServer) error
}

// UnimplementedCalculatorServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCalculatorServiceServer struct {
}

func (*UnimplementedCalculatorServiceServer) Sum(ctx context.Context, req *SumRequest) (*SumResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sum not implemented")
}
func (*UnimplementedCalculatorServiceServer) PrimeNumbers(req *PrimeNumbersRequest, srv CalculatorService_PrimeNumbersServer) error {
	return status.Errorf(codes.Unimplemented, "method PrimeNumbers not implemented")
}

func RegisterCalculatorServiceServer(s *grpc.Server, srv CalculatorServiceServer) {
	s.RegisterService(&_CalculatorService_serviceDesc, srv)
}

func _CalculatorService_Sum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculatorServiceServer).Sum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calculator.CalculatorService/Sum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculatorServiceServer).Sum(ctx, req.(*SumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalculatorService_PrimeNumbers_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PrimeNumbersRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CalculatorServiceServer).PrimeNumbers(m, &calculatorServicePrimeNumbersServer{stream})
}

type CalculatorService_PrimeNumbersServer interface {
	Send(*PrimeNumbersResponse) error
	grpc.ServerStream
}

type calculatorServicePrimeNumbersServer struct {
	grpc.ServerStream
}

func (x *calculatorServicePrimeNumbersServer) Send(m *PrimeNumbersResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _CalculatorService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "calculator.CalculatorService",
	HandlerType: (*CalculatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sum",
			Handler:    _CalculatorService_Sum_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PrimeNumbers",
			Handler:       _CalculatorService_PrimeNumbers_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "calculator/calculatorpb/calculator.proto",
}
