service: eventbridge-demo
frameworkVersion: '>=1.28.0 <2.0.0'

provider:
  name: aws
  runtime: go1.x
  region: us-east-1
  memorySize: 128
  timeout: 5
  endpointType: regional
  environment:
    EVENTBUS_NAME: AliceBob
    ALICES_BUCKET_NAME: alices-files-bucket
    BOBS_BUCKET_NAME: bobs-files-bucket
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'events:PutEvents'
      Resource: "*"
    - Effect: 'Allow'
      Action:
        - 's3:*'
      Resource: '*'
  # profile: saml


package:
  exclude:
    - ./**
  include:
    - ./build/**

functions:
  alice:
    handler: build/alice
    description: Receives S3 events and sends to EventBridge
    events:
      - s3: ${self:provider.environment.ALICES_BUCKET_NAME}
        event: s3:ObjectCreated:*
        rules:
          - suffix: .xlsx
  bob:
    handler: build/bob
    description: Receives events from the EventBridge
    events:
      - eventBridge:
          eventBus: ${self:provider.environment.EVENTBUS_NAME}
          pattern:
            source:
              - bob.wakeUp
resources:
  Resources:
    BobsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.BOBS_BUCKET_NAME}