service: eventbridge-demo
frameworkVersion: '>=1.28.0 <2.0.0'

provider:
  name: aws
  runtime: go1.x
  region: us-east-1
  memorySize: 128
  timeout: 5
  endpointType: regional
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "events:PutEvents"
      Resource: "*"


package:
  exclude:
    - ./**
  include:
    - ./build/**

functions:
  alice:
    handler: build/alice
    description: Receives http GET requests and sends to EventBridge
    events:
      - http:
          path: alice
          method: get
  bob:
    handler: build/bob
    description: Receives events from the EventBridge