service: eventbridge-demo
frameworkVersion: '>=1.28.0 <2.0.0'

provider:
  name: aws
  runtime: go1.x
  region: us-east-1
  memorySize: 128
  timeout: 5
  endpointType: regional
  environment:
    EVENTBUS_NAME: AliceBob
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "events:PutEvents"
      Resource: "*"
  profile: saml


package:
  exclude:
    - ./**
  include:
    - ./build/**

functions:
  alice:
    handler: build/alice
    description: Receives S3 events and sends to EventBridge
    events:
      - s3: alices-files
        events: 
          - s3:ObjectCreated:*
      # - http:
      #     path: alice
      #     method: get
  bob:
    handler: build/bob
    description: Receives events from the EventBridge
    events:
      - eventBridge:
          eventBus: "${self:provider.environment.EVENTBUS_NAME}"
          pattern:
            source:
              - bob.wakeUp