version: "3.6"
services:
  src:
    container_name: src
    build: 
      context: ./code
      dockerfile: Dockerfile
    volumes:
      - ./code:/code
    working_dir: /code
    extra_hosts:
      - "local.regeneron.regn.com:192.168.99.100"