version: '2'

networks:
  airline:

services:
  # Orderer
  orderer.acme.com:
    container_name: orderer.acme.com
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - FABRIC_CFG_PATH=/var/hyperledger/config
      # - ORDERER_GENERAL_LOGLEVEL=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=orderer.acme.com
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/genesis/airline-genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/msp
      - ORDERER_FILELEDGER_LOCATION=/var/ledger
    working_dir: $HOME
    command: orderer
    volumes:
    # Folder with genesis block
    - ${PWD}/config/orderer:/var/hyperledger/genesis
    # Map the folder with MSP for orderer
    - ${PWD}/client/orderer/orderer//msp:/var/hyperledger/msp
    # Map the current folder to cfg
    - ${PWD}/config/orderer:/var/hyperledger/config
    - ${HOME}/ledgers/ca/orderer.acme.com:/var/ledger
    ports:
      - 7050:7050
    networks:
      - airline

  # Acme peer1
  acme-peer1.acme.com:
    container_name: acme-peer1.acme.com
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      - FABRIC_CFG_PATH=/var/hyperledger/config
      # - CORE_LOGGING_LEVEL=debug
      - FABRIC_LOGGING_SPEC=DEBUG

      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock

      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_airline

      - CORE_PEER_ID=acme-peer1.acme.com
      # - CORE_PEER_LISTENADDRESS=budget-peer1.budget.com:7051
      - CORE_PEER_ADDRESS=acme-peer1.acme.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=acme-peer1.acme.com:7051
      # - CORE_PEER_ADDRESS=0.0.0.0:7051
      # - CORE_PEER_GOSSIP_EXTERNALENDPOINT=0.0.0.0:7051

      - CORE_PEER_LOCALMSPID=AcmeMSP
      - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/msp
      - CORE_PEER_TLS_ENABLED=false
      # - CORE_PEER_GOSSIP_USELEADERELECTION=true
      # - CORE_PEER_GOSSIP_ORGLEADER=false
      # - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_FILESYSTEMPATH=/var/ledger
    working_dir: $HOME
    # command: peer node start --peer-chaincodedev=true
    command: peer node start

    volumes:
      # Folder with channel create tx file
      - ${PWD}/config:/var/hyperledger/channeltx
      # Map the folder with MSP for Peer
      - ${PWD}/client/acme/peer1/msp:/var/hyperledger/msp
      # Map the current folder to cfg
      - ${PWD}/config:/var/hyperledger/config
      - /var/run/:/host/var/run/
      # Ledger folder for the peer
      - ${HOME}/ledgers/ca/acme-peer1.acme.com/:/var/ledger
    depends_on: 
      - orderer.acme.com
    ports:
      - 7051:7051
      - 7052:7052
      - 7053:7053
    networks:
      - airline

  # Budget peer1
  budget-peer1.budget.com:
    container_name: budget-peer1.budget.com
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      - FABRIC_CFG_PATH=/var/hyperledger/config
      # - CORE_LOGGING_LEVEL=debug
      - FABRIC_LOGGING_SPEC=INFO

      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock

      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_airline

      - CORE_PEER_ID=budget-peer1.budget.com
      - CORE_PEER_ADDRESS=budget-peer1.budget.com:8051
      # - CORE_PEER_LISTENADDRESS=budget-peer1.budget.com:8051
      - CORE_PEER_LISTENADDRESS=budget-peer1.budget.com:8051
      - CORE_PEER_CHAINCODELISTENADDRESS=budget-peer1.budget.com:8052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=budget-peer1.budget.com:8051
      - CORE_PEER_LOCALMSPID=BudgetMSP
      - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/msp
      - CORE_PEER_TLS_ENABLED=false
      # - CORE_PEER_GOSSIP_USELEADERELECTION=true
      # - CORE_PEER_GOSSIP_ORGLEADER=false
      # - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_FILESYSTEMPATH=/var/ledger
    working_dir: $HOME
    # command: peer node start --peer-chaincodedev=true
    command: peer node start

    volumes:
      # Folder with channel create tx file
      - ${PWD}/config:/var/hyperledger/channeltx
      # Map the folder with MSP for Peer
      - ${PWD}/client/budget/peer1/msp:/var/hyperledger/msp
      # Map the current folder to cfg
      - ${PWD}/config:/var/hyperledger/config
      - /var/run/:/host/var/run/
      # Ledger folder for the peer
      - ${HOME}/ledgers/ca/budget-peer1.budget.com:/var/ledger
    depends_on: 
      - orderer.acme.com
    ports:
      - 8051:8051
      - 8052:8052
      - 8053:8053
    networks:
      - airline

  