AWSTemplateFormatVersion: '2010-09-09'
Globals:
  Function:
    Environment:
      Variables:
        TABLE_NAME:
          Ref: Table
    Handler: main
    MemorySize: 128
    Runtime: go1.x
    Timeout: 5
Resources:
  DeleteUser:
    Properties:
      CodeUri: s3://romel-sam/9eb6e245a0810575607950bb6abe7c04
      Events:
        GetUser:
          Properties:
            Method: delete
            Path: /user/{userid}
          Type: Api
      Policies: AmazonDynamoDBFullAccess
    Type: AWS::Serverless::Function
  GetUser:
    Properties:
      CodeUri: s3://romel-sam/9bfa7d9c4fd620d6b2f5cd93546b2de3
      Events:
        GetUser:
          Properties:
            Method: get
            Path: /user/{userid}
          Type: Api
      Policies: AmazonDynamoDBReadOnlyAccess
    Type: AWS::Serverless::Function
  PostUser:
    Properties:
      CodeUri: s3://romel-sam/8f644448dced7d68f307cd3832987ff4
      Events:
        GetUser:
          Properties:
            Method: post
            Path: /user/{userid}
          Type: Api
      Policies: AmazonDynamoDBFullAccess
    Type: AWS::Serverless::Function
  Table:
    Properties:
      PrimaryKey:
        Name: userid
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
    Type: AWS::Serverless::SimpleTable
Transform: AWS::Serverless-2016-10-31
