CONFIG = {
    "test_size": 0.2,
    "random_state": 42,
    "outlier_threshold": 3,
    "figure_size": (12, 8),
    "point_color": "blue",
    "test_point_color": "green",
    "line_color": "red",
    "plane_color": "cyan",
    "line_width": 2,
    "grid_alpha": 0.3,
    "point_alpha": 0.7,
    "plane_alpha": 0.5,
    "mesh_grid_size": 20,
    "default_csv": "house_data.csv",
    "output_image": "housing_regression_2d.png",
    "output_3d_image": "housing_regression_3d.png",
    "default_model_path": "housing_model.pkl",
    "default_metadata_path": "housing_model_metadata.json",
    "required_columns": ["square_footage", "bedrooms", "price_thousands"],
    "feature_columns": ["square_footage", "bedrooms"],
    "target_column": "price_thousands",
}
