#
# Build go project
#
FROM golang:1.18-alpine as go-builder

WORKDIR /app

COPY . .

RUN apk add -u -t build-tools curl git && \
    go build -o server *.go && \
    apk del build-tools && \
    rm -rf /var/cache/apk/*

#
# Runtime container
#
FROM SCRATCH

COPY --from=go-builder /app/server /server

EXPOSE 8080

ENTRYPOINT ["/server"]
