# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  run:
    desc: Run main.go
    cmds:
      - go run main/main.go
  test:
    desc: Run go tests
    cmds:
      - go test ./...    
