version: 0.2

phases:
  install:
    commands:
      - echo Installing Serverless
      - npm install -g serverless
  pre_build:
    commands:
      - echo 'Additional plugins serverless-offline, serverless-dotenv-plugin, serverless-domain-manager and serverless-dynamodb-ttl'
      # - npm install serverless-offline --save-dev
      # - npm i -D serverless-dotenv-plugin
      # - npm install serverless-domain-manager --save-dev
      # - npm install serverless-dynamodb-ttl --save
  build:
    commands:
      - echo Deployment started on `date`
      - echo Deploying with Serverless Framework
      - sls deploy -v -s $ENV_NAME
  post_build:
    commands:
      - echo Deployment completed on `date`