# https://taskfile.dev

version: '3'

vars:
  TABLE: barjokes


tasks:
  run:
    desc: run program
    cmds:
      - go run main.go
    silent: true

  show:
    desc: Show items
    cmds:
      - aws dynamodb scan --table-name {{.TABLE}}