version: '3'

tasks:
  build_hello:
    dir: '.'
    cmds:
      - protoc --go_out=. --go-grpc_out=. ./hello/*.proto
      - go mod tidy
  build_payment:
    dir: '.'
    cmds:
      - protoc --go_out=.  ./payment/*.proto
      - go mod tidy
  build_transaction:
    dir: '.'
    cmds:
      - protoc --go_out=. ./transaction/*.proto
      - go mod tidy
  build_bank:
    dir: '.'
    cmds:
      - protoc --go_out=. --go-grpc_out=. ./bank/type/*.proto ./bank/*.proto
      - go mod tidy
  build_resiliency:
    dir: '.'
    cmds:
      - protoc --go_out=. --go-grpc_out=. ./resiliency/type/*.proto ./resiliency/*.proto
      - go mod tidy
  clean_gateway:
    dir: '.'
    cmds:
      - rm -fR ./protogen/gateway 
      - mkdir -p ./protogen/gateway/go
      - mkdir -p ./protogen/gateway/openapiv2
  protoc_go_gateway:
    dir: '.'
    cmds: 
      - protoc -I .  --grpc-gateway_out ./protogen/gateway/go --grpc-gateway_opt logtostderr=true --grpc-gateway_opt paths=source_relative --grpc-gateway_opt grpc_api_configuration=./grpc-gateway/config.yml --grpc-gateway_opt standalone=true --grpc-gateway_opt generate_unbound_methods=true ./hello/*.proto ./bank/*.proto ./bank/type/*.proto ./resiliency/*.proto
  protoc_openapiv2_gateway:
    dir: '.'
    cmds:
      - protoc -I . --openapiv2_out ./protogen/gateway/openapiv2 --openapiv2_opt logtostderr=true --openapiv2_opt output_format=yaml --openapiv2_opt grpc_api_configuration=./grpc-gateway/config.yml --openapiv2_opt openapi_configuration=./grpc-gateway/config-openapi.yml --openapiv2_opt generate_unbound_methods=true --openapiv2_opt allow_merge=true --openapiv2_opt merge_file_name=merged ./hello/*.proto ./bank/*.proto ./bank/type/*.proto ./resiliency/*.proto ./resiliency/type/*.proto
  build_gateway:
    cmds:
      - task clean_gateway
      - task protoc_go_gateway
      - task protoc_openapiv2_gateway
  build:
    cmds:
      - task build_hello
      - task build_payment
      - task build_transaction
      - task build_bank
      - task build_resiliency
      - task build_gateway
