version: '3'

tasks:
  build_hello:
    dir: '.'
    cmds:
      - protoc --go_out=. --go-grpc_out=. ./hello/*.proto
      - go mod tidy
  build_payment:
    dir: '.'
    cmds:
      - protoc --go_out=.  ./payment/*.proto
      - go mod tidy
  build_transaction:
    dir: '.'
    cmds:
      - protoc --go_out=. ./transaction/*.proto
      - go mod tidy
  build:
    cmds:
      - task build_hello
      - task build_payment
      - task build_transaction
