version: '3'

tasks:
  build_hello:
    dir: '.'
    cmds:
      - protoc --go_out=./protogen --go-grpc_out=. --go_opt=paths=source_relative ./hello/*.proto
      - go mod tidy
  build_payment:
    dir: '.'
    cmds:
      - protoc --go_out=./protogen --go_opt=paths=source_relative ./payment/*.proto
      - go mod tidy
  build_transaction:
    dir: '.'
    cmds:
      - protoc --go_out=./protogen --go_opt=paths=source_relative ./transaction/*.proto
      - go mod tidy
  build:
    cmds:
      - task build_hello
      - task build_payment
      - task build_transaction
