version: '3'

tasks:
  build_hello:
    dir: './protogen'
    cmds:
      - protoc --go_out=. --go-grpc_out=. --go_opt=paths=source_relative --go-grpc_opt=paths=source_relative --proto_path=.. ../hello/*.proto
      - go mod tidy
  build_payment:
    dir: './protogen'
    cmds:
      - protoc --go_out=. --go_opt=paths=source_relative --proto_path=.. ../payment/*.proto
      - go mod tidy
  build_transaction:
    dir: './protogen'
    cmds:
      - protoc --go_out=. --go_opt=paths=source_relative --proto_path=.. ../transaction/*.proto
      - go mod tidy
  build:
    cmds:
      - task build_hello
      - task build_payment
      - task build_transaction
