version: "2"
services:
  node:
    build:
      context: .
      dockerfile: ./Dockerfile    
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./:/home/node/app
    ports:
      - "3000:3000"