version: "2"
services:
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile    
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./client:/home/node/app
    ports:
      - "3000:3000"
  api:
    container_name: api
    build: 
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./api:/go/src/github.com/GOCODE/udemy/RealTime
    working_dir: /go/src/github.com/GOCODE/udemy/RealTime