apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-k8s-client
  labels:
    io.kompose.service: simple-k8s-client
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: simple-k8s-client
  template:
    metadata:
      labels:
        io.kompose.service: simple-k8s-client
    spec:
      containers:
      - name: simple-k8s-client
        image: "rcampbell/simple-k8s-client:1.0.1"
        imagePullPolicy: Always
        env:
        - name: SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: simple-k8s-config
              key: service.url

        resources:
          requests:
            memory: "64Mi"
            cpu: "125m"
          limits:
            memory: "128Mi"
            cpu: "250m"