apiVersion: v1
kind: Service
metadata:
  labels:
  name: camera
  namespace: default
spec:
  ports:
  - nodePort: 31589
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    run: camera
  type: NodePort