version: "2"
services:
    golang:
      container_name: golang
      build:
        context: ./rpi/golang/
        dockerfile: go.dockerfile
    gobot:
      container_name: gobot
      build:
        context: ./rpi/gobot/
        dockerfile: gobot.dockerfile
    camera:
      container_name: camera
      build:
        context: .
        dockerfile: Dockerfile
      ports: 
        - "3000:3000"
      working_dir: /var/app
      command:  >
        /bin/sh -c "
          go build camera.go && 
          ./camera"
      volumes:
        - .:/var/app