apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: work-queue
    component: queue
    chapter: jobs
  name: consumers
spec:
  parallelism: 5
  template:
    metadata:
      labels:
        app: work-queue
        component: queue
        chapter: jobs
    spec:
        containers:
        - name: worker
          image: gcr.io/kuar-demo/kuard-arm:1
          imagePullPolicy: Always
          args:
          - "--keygen-enable"
          - "--keygen-exit-on-complete"
          - "--keygen-memq-server=http://queue:8080/memq/server"
          - "--keygen-memq-queue=keygen"
        restartPolicy: OnFailure