service: sls-state-machine
frameworkVersion: '>=1.28.0 <2.0.0'

plugins:
  - serverless-step-functions

provider:
  name: aws
  stage: dev 
  region: us-east-1
  endpointType: regional

stepFunctions:
  stateMachines:
    HelloStepFunc:
        definition:
          Comment: "HelloWorld example"
          StartAt: WaitFormSomeTime
          States:
            WaitFormSomeTime:
              Comment: "Wait state"
              Type: Wait
              SecondsPath: $.WaitTime
              Next: SquareNumber
            SquareNumber:
              Comment: "return square of the number"
              Type: Task
              Resource: arn:aws:lambda:us-east-1:132172135366:function:calculateSquare
              TimeoutSeconds: 10
              Next: HelloWorld
            HelloWorld:
              Comment: "Hello World Step"
              Type: Pass
              # InputPath: $.answer
              End: true