// Code generated by protoc-gen-go. DO NOT EDIT.
// source: blog/blogpb/blog.proto

package blogpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Blog struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AuthorId             string   `protobuf:"bytes,2,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content              string   `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Blog) Reset()         { *m = Blog{} }
func (m *Blog) String() string { return proto.CompactTextString(m) }
func (*Blog) ProtoMessage()    {}
func (*Blog) Descriptor() ([]byte, []int) {
	return fileDescriptor_a4b0406114889fe6, []int{0}
}

func (m *Blog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Blog.Unmarshal(m, b)
}
func (m *Blog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Blog.Marshal(b, m, deterministic)
}
func (m *Blog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Blog.Merge(m, src)
}
func (m *Blog) XXX_Size() int {
	return xxx_messageInfo_Blog.Size(m)
}
func (m *Blog) XXX_DiscardUnknown() {
	xxx_messageInfo_Blog.DiscardUnknown(m)
}

var xxx_messageInfo_Blog proto.InternalMessageInfo

func (m *Blog) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Blog) GetAuthorId() string {
	if m != nil {
		return m.AuthorId
	}
	return ""
}

func (m *Blog) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Blog) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type CreateBlogRequets struct {
	Blog                 *Blog    `protobuf:"bytes,1,opt,name=blog,proto3" json:"blog,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBlogRequets) Reset()         { *m = CreateBlogRequets{} }
func (m *CreateBlogRequets) String() string { return proto.CompactTextString(m) }
func (*CreateBlogRequets) ProtoMessage()    {}
func (*CreateBlogRequets) Descriptor() ([]byte, []int) {
	return fileDescriptor_a4b0406114889fe6, []int{1}
}

func (m *CreateBlogRequets) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBlogRequets.Unmarshal(m, b)
}
func (m *CreateBlogRequets) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBlogRequets.Marshal(b, m, deterministic)
}
func (m *CreateBlogRequets) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBlogRequets.Merge(m, src)
}
func (m *CreateBlogRequets) XXX_Size() int {
	return xxx_messageInfo_CreateBlogRequets.Size(m)
}
func (m *CreateBlogRequets) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBlogRequets.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBlogRequets proto.InternalMessageInfo

func (m *CreateBlogRequets) GetBlog() *Blog {
	if m != nil {
		return m.Blog
	}
	return nil
}

type CreateBlogResponse struct {
	Blog                 *Blog    `protobuf:"bytes,1,opt,name=blog,proto3" json:"blog,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBlogResponse) Reset()         { *m = CreateBlogResponse{} }
func (m *CreateBlogResponse) String() string { return proto.CompactTextString(m) }
func (*CreateBlogResponse) ProtoMessage()    {}
func (*CreateBlogResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a4b0406114889fe6, []int{2}
}

func (m *CreateBlogResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBlogResponse.Unmarshal(m, b)
}
func (m *CreateBlogResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBlogResponse.Marshal(b, m, deterministic)
}
func (m *CreateBlogResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBlogResponse.Merge(m, src)
}
func (m *CreateBlogResponse) XXX_Size() int {
	return xxx_messageInfo_CreateBlogResponse.Size(m)
}
func (m *CreateBlogResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBlogResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBlogResponse proto.InternalMessageInfo

func (m *CreateBlogResponse) GetBlog() *Blog {
	if m != nil {
		return m.Blog
	}
	return nil
}

type ReadBlogRequets struct {
	BlogId               *Blog    `protobuf:"bytes,1,opt,name=blog_id,json=blogId,proto3" json:"blog_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadBlogRequets) Reset()         { *m = ReadBlogRequets{} }
func (m *ReadBlogRequets) String() string { return proto.CompactTextString(m) }
func (*ReadBlogRequets) ProtoMessage()    {}
func (*ReadBlogRequets) Descriptor() ([]byte, []int) {
	return fileDescriptor_a4b0406114889fe6, []int{3}
}

func (m *ReadBlogRequets) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadBlogRequets.Unmarshal(m, b)
}
func (m *ReadBlogRequets) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadBlogRequets.Marshal(b, m, deterministic)
}
func (m *ReadBlogRequets) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadBlogRequets.Merge(m, src)
}
func (m *ReadBlogRequets) XXX_Size() int {
	return xxx_messageInfo_ReadBlogRequets.Size(m)
}
func (m *ReadBlogRequets) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadBlogRequets.DiscardUnknown(m)
}

var xxx_messageInfo_ReadBlogRequets proto.InternalMessageInfo

func (m *ReadBlogRequets) GetBlogId() *Blog {
	if m != nil {
		return m.BlogId
	}
	return nil
}

type ReadBlogResponse struct {
	Blog                 *Blog    `protobuf:"bytes,1,opt,name=blog,proto3" json:"blog,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadBlogResponse) Reset()         { *m = ReadBlogResponse{} }
func (m *ReadBlogResponse) String() string { return proto.CompactTextString(m) }
func (*ReadBlogResponse) ProtoMessage()    {}
func (*ReadBlogResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a4b0406114889fe6, []int{4}
}

func (m *ReadBlogResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadBlogResponse.Unmarshal(m, b)
}
func (m *ReadBlogResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadBlogResponse.Marshal(b, m, deterministic)
}
func (m *ReadBlogResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadBlogResponse.Merge(m, src)
}
func (m *ReadBlogResponse) XXX_Size() int {
	return xxx_messageInfo_ReadBlogResponse.Size(m)
}
func (m *ReadBlogResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadBlogResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadBlogResponse proto.InternalMessageInfo

func (m *ReadBlogResponse) GetBlog() *Blog {
	if m != nil {
		return m.Blog
	}
	return nil
}

func init() {
	proto.RegisterType((*Blog)(nil), "blog.Blog")
	proto.RegisterType((*CreateBlogRequets)(nil), "blog.CreateBlogRequets")
	proto.RegisterType((*CreateBlogResponse)(nil), "blog.CreateBlogResponse")
	proto.RegisterType((*ReadBlogRequets)(nil), "blog.ReadBlogRequets")
	proto.RegisterType((*ReadBlogResponse)(nil), "blog.ReadBlogResponse")
}

func init() { proto.RegisterFile("blog/blogpb/blog.proto", fileDescriptor_a4b0406114889fe6) }

var fileDescriptor_a4b0406114889fe6 = []byte{
	// 265 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x51, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x25, 0x31, 0xa6, 0xe9, 0x14, 0xfc, 0x18, 0xb4, 0x2e, 0x15, 0x44, 0xe2, 0xc5, 0x53, 0x85,
	0x54, 0x04, 0x4f, 0x42, 0x3d, 0xf5, 0x1a, 0x6f, 0x5e, 0x4a, 0x92, 0x1d, 0xea, 0x42, 0xc8, 0xc6,
	0xcd, 0xd6, 0xff, 0xe0, 0xbf, 0x96, 0x9d, 0x6d, 0x69, 0x6d, 0x0e, 0x7a, 0xd9, 0x9d, 0x79, 0x33,
	0x8f, 0xf7, 0x1e, 0x03, 0xe3, 0xb2, 0xd6, 0xab, 0x07, 0xf7, 0xb4, 0x25, 0x7f, 0xd3, 0xd6, 0x68,
	0xab, 0x31, 0x72, 0x75, 0x5a, 0x41, 0x34, 0xaf, 0xf5, 0x0a, 0x4f, 0x20, 0x54, 0x52, 0x04, 0xb7,
	0xc1, 0xfd, 0x30, 0x0f, 0x95, 0xc4, 0x6b, 0x18, 0x16, 0x6b, 0xfb, 0xa1, 0xcd, 0x52, 0x49, 0x11,
	0x32, 0x9c, 0x78, 0x60, 0x21, 0xf1, 0x02, 0x8e, 0xad, 0xb2, 0x35, 0x89, 0x23, 0x1e, 0xf8, 0x06,
	0x05, 0x0c, 0x2a, 0xdd, 0x58, 0x6a, 0xac, 0x88, 0x18, 0xdf, 0xb6, 0xe9, 0x0c, 0xce, 0x5f, 0x0d,
	0x15, 0x96, 0x9c, 0x54, 0x4e, 0x9f, 0x6b, 0xb2, 0x1d, 0xde, 0x00, 0x3b, 0x60, 0xcd, 0x51, 0x06,
	0x53, 0xb6, 0xc6, 0x0b, 0xde, 0xd9, 0x23, 0xe0, 0x3e, 0xa9, 0x6b, 0x75, 0xd3, 0xd1, 0x9f, 0xac,
	0x27, 0x38, 0xcd, 0xa9, 0x90, 0xfb, 0x42, 0x77, 0x30, 0x70, 0xa3, 0xe5, 0x26, 0xdf, 0x6f, 0x56,
	0xec, 0xca, 0x85, 0x4c, 0x33, 0x38, 0xdb, 0xf1, 0xfe, 0xa7, 0x95, 0x7d, 0x07, 0x30, 0x72, 0xed,
	0x1b, 0x99, 0x2f, 0x55, 0x11, 0xbe, 0x00, 0xec, 0x1c, 0xe3, 0x95, 0xdf, 0xef, 0x05, 0x9f, 0x88,
	0xfe, 0x60, 0x23, 0xf8, 0x0c, 0xc9, 0xd6, 0x04, 0x5e, 0xfa, 0xad, 0x83, 0x30, 0x93, 0xf1, 0x21,
	0xec, 0xa9, 0xf3, 0xe4, 0x3d, 0xf6, 0x27, 0x2e, 0x63, 0x3e, 0xef, 0xec, 0x27, 0x00, 0x00, 0xff,
	0xff, 0x22, 0x53, 0x89, 0xa6, 0xf8, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BlogServiceClient is the client API for BlogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BlogServiceClient interface {
	CreateBlog(ctx context.Context, in *CreateBlogRequets, opts ...grpc.CallOption) (*CreateBlogResponse, error)
	ReadBlog(ctx context.Context, in *ReadBlogRequets, opts ...grpc.CallOption) (*ReadBlogResponse, error)
}

type blogServiceClient struct {
	cc *grpc.ClientConn
}

func NewBlogServiceClient(cc *grpc.ClientConn) BlogServiceClient {
	return &blogServiceClient{cc}
}

func (c *blogServiceClient) CreateBlog(ctx context.Context, in *CreateBlogRequets, opts ...grpc.CallOption) (*CreateBlogResponse, error) {
	out := new(CreateBlogResponse)
	err := c.cc.Invoke(ctx, "/blog.BlogService/CreateBlog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogServiceClient) ReadBlog(ctx context.Context, in *ReadBlogRequets, opts ...grpc.CallOption) (*ReadBlogResponse, error) {
	out := new(ReadBlogResponse)
	err := c.cc.Invoke(ctx, "/blog.BlogService/ReadBlog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlogServiceServer is the server API for BlogService service.
type BlogServiceServer interface {
	CreateBlog(context.Context, *CreateBlogRequets) (*CreateBlogResponse, error)
	ReadBlog(context.Context, *ReadBlogRequets) (*ReadBlogResponse, error)
}

// UnimplementedBlogServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBlogServiceServer struct {
}

func (*UnimplementedBlogServiceServer) CreateBlog(ctx context.Context, req *CreateBlogRequets) (*CreateBlogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBlog not implemented")
}
func (*UnimplementedBlogServiceServer) ReadBlog(ctx context.Context, req *ReadBlogRequets) (*ReadBlogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadBlog not implemented")
}

func RegisterBlogServiceServer(s *grpc.Server, srv BlogServiceServer) {
	s.RegisterService(&_BlogService_serviceDesc, srv)
}

func _BlogService_CreateBlog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBlogRequets)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServiceServer).CreateBlog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blog.BlogService/CreateBlog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServiceServer).CreateBlog(ctx, req.(*CreateBlogRequets))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlogService_ReadBlog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadBlogRequets)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServiceServer).ReadBlog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blog.BlogService/ReadBlog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServiceServer).ReadBlog(ctx, req.(*ReadBlogRequets))
	}
	return interceptor(ctx, in, info, handler)
}

var _BlogService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "blog.BlogService",
	HandlerType: (*BlogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBlog",
			Handler:    _BlogService_CreateBlog_Handler,
		},
		{
			MethodName: "ReadBlog",
			Handler:    _BlogService_ReadBlog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "blog/blogpb/blog.proto",
}
