version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.16
      nodejs: 12
    commands:
      - echo Installing CDK..
      - npm i cdk@v2.1.0 -g
      - go get -u github.com/jstemmer/go-junit-report      
  build:
    commands:
      - echo Testing app...
      - cd $CODEBUILD_SRC_DIR/architectures/serverless/app
      - go test -v  2>&1 | go-junit-report >$CODEBUILD_SRC_DIR/report-app.xml
      - env GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o dist/main main/main.go
      - chmod +x dist/main
      - cd dist && zip main.zip main
      - echo Testing infra...
      - cd $CODEBUILD_SRC_DIR/architectures/serverless/infra
      - go test -v  2>&1 | go-junit-report >$CODEBUILD_SRC_DIR/report-infra.xml

reports:
  gotest_reports:
    files:
      - report-app.xml
      - report-infra.xml
    base-directory: $CODEBUILD_SRC_DIR
    file-format: JUNITXML

 