version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.16
      nodejs: 14
    commands:
      - echo Installing CDK..
      - npm i cdk@v2.1.0 -g
      - go get -u github.com/jstemmer/go-junit-report      
  build:
    commands:
      - echo Unit Testing app...
      - cd $CODEBUILD_SRC_DIR/architectures/serverless/app
      - go test -v  2>&1 | go-junit-report >$CODEBUILD_SRC_DIR/report-app.xml
      - env GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o dist/main main/main.go
      - chmod +x dist/main
      - cd dist && zip main.zip main
      - echo Unit Testing infra...
      - cd $CODEBUILD_SRC_DIR/architectures/serverless/infra
      - go test -v  2>&1 | go-junit-report >$CODEBUILD_SRC_DIR/report-infra.xml
  post_build:
    commands:
      - echo Deploying infra
      - cd $CODEBUILD_SRC_DIR/architectures/serverless/infra
      - cdk deploy --require-approval never
      - echo Integration Testing infra...
      - export I_TEST=yes &&  go test -v  2>&1 | go-junit-report >$CODEBUILD_SRC_DIR/report-infra-integration.xml
      - cd $CODEBUILD_SRC_DIR/architectures/serverless/app
      - echo Integration Testing App...
      - export I_TEST=yes && go test -v  2>&1 | go-junit-report >$CODEBUILD_SRC_DIR/report-app-integration.xml
      - cd $CODEBUILD_SRC_DIR/architectures/serverless/infra
      - echo Destroying infra
      - cdk destroy -f
      

reports:
  gotest_reports:
    files:
      - report-app.xml
      - report-infra.xml
      - report-app-integration.xml
      - report-infra-integration.xml
    base-directory: $CODEBUILD_SRC_DIR
    file-format: JUNITXML

 
