# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"
  config.vm.define "master" do |k3s|
      k3s.vm.hostname = "master"
      k3s.vm.network "private_network", ip: "192.168.33.111"
      k3s.vm.network "forwarded_port", guest: 6443, host: 6443, host_ip: "0.0.0.0"
      k3s.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.name = "master"
      end
      
      k3s.vm.provision "shell", inline: <<-SHELL
        hostnamectl set-hostname master
        curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.17.11+k3s1 sh -
        systemctl stop k3s
        cp /vagrant/master.service /etc/systemd/system/k3s.service 
        sed -i -e "s#server#server --write-kubeconfig-mode 644 #g" /etc/systemd/system/k3s.service
        systemctl daemon-reload
        systemctl start k3s        
        NODE_TOKEN="/var/lib/rancher/k3s/server/node-token"
        while [ ! -e ${NODE_TOKEN} ]
        do
            echo "Waiting for node token..."
            sleep 1
        done
        echo "Node token ready!"
        cat ${NODE_TOKEN}
        cp ${NODE_TOKEN} /vagrant/
      SHELL
  end

  config.vm.define "node01" do |k3s|
      k3s.vm.hostname = "node01"
      k3s.vm.network "private_network", ip: "192.168.33.112"
      k3s.vm.network "forwarded_port", guest: 6444, host: 6444, host_ip: "0.0.0.0"
      k3s.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.name = "node01"
      end

      k3s.vm.provision "shell", inline: <<-SHELL
        # curl -sfL https://get.k3s.io | K3S_URL=https://192.168.33.111:6443  K3S_TOKEN=$(cat /vagrant/node-token) sh - 
        hostnamectl set-hostname node01
        curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.17.11+k3s1 sh -
        systemctl stop k3s
        cp /vagrant/master.service /etc/systemd/system/k3s.service 
        sed -i -e "s#server#agent --docker --no-flannel --node-name node01 --node-ip 192.168.33.112 --server https://192.168.33.111:6443 --token $(cat /vagrant/node-token) --with-node-id --write-kubeconfig-mode 644 #g" /etc/systemd/system/k3s.service
        cp /etc/systemd/system/k3s.service /vagrant/agent.service
        systemctl daemon-reload
        systemctl start k3s
      SHELL
  end
end
