// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.4
// source: jobsearch/jobsearch.proto

package jobsearch

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	basic "project01/proto/basic/protogen/basic"
	dummy "project01/proto/dummy/protogen/dummy"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobCandidate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobCandidateId uint32             `protobuf:"varint,1,opt,name=job_candidate_id,proto3" json:"job_candidate_id,omitempty"`
	Application    *dummy.Application `protobuf:"bytes,2,opt,name=application,proto3" json:"application,omitempty"`
}

func (x *JobCandidate) Reset() {
	*x = JobCandidate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jobsearch_jobsearch_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobCandidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobCandidate) ProtoMessage() {}

func (x *JobCandidate) ProtoReflect() protoreflect.Message {
	mi := &file_jobsearch_jobsearch_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobCandidate.ProtoReflect.Descriptor instead.
func (*JobCandidate) Descriptor() ([]byte, []int) {
	return file_jobsearch_jobsearch_proto_rawDescGZIP(), []int{0}
}

func (x *JobCandidate) GetJobCandidateId() uint32 {
	if x != nil {
		return x.JobCandidateId
	}
	return 0
}

func (x *JobCandidate) GetApplication() *dummy.Application {
	if x != nil {
		return x.Application
	}
	return nil
}

type JobSoftware struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobSoftwareId uint32             `protobuf:"varint,1,opt,name=job_software_id,proto3" json:"job_software_id,omitempty"`
	Application   *basic.Application `protobuf:"bytes,2,opt,name=application,proto3" json:"application,omitempty"`
}

func (x *JobSoftware) Reset() {
	*x = JobSoftware{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jobsearch_jobsearch_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobSoftware) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobSoftware) ProtoMessage() {}

func (x *JobSoftware) ProtoReflect() protoreflect.Message {
	mi := &file_jobsearch_jobsearch_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobSoftware.ProtoReflect.Descriptor instead.
func (*JobSoftware) Descriptor() ([]byte, []int) {
	return file_jobsearch_jobsearch_proto_rawDescGZIP(), []int{1}
}

func (x *JobSoftware) GetJobSoftwareId() uint32 {
	if x != nil {
		return x.JobSoftwareId
	}
	return 0
}

func (x *JobSoftware) GetApplication() *basic.Application {
	if x != nil {
		return x.Application
	}
	return nil
}

var File_jobsearch_jobsearch_proto protoreflect.FileDescriptor

var file_jobsearch_jobsearch_proto_rawDesc = []byte{
	0x0a, 0x19, 0x6a, 0x6f, 0x62, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2f, 0x6a, 0x6f, 0x62, 0x73,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x62, 0x61, 0x73,
	0x69, 0x63, 0x2f, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x64, 0x75, 0x6d, 0x6d, 0x79, 0x2f, 0x61, 0x70, 0x70, 0x6c,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x74, 0x0a,
	0x0c, 0x4a, 0x6f, 0x62, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x12, 0x2a, 0x0a,
	0x10, 0x6a, 0x6f, 0x62, 0x5f, 0x63, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x10, 0x6a, 0x6f, 0x62, 0x5f, 0x63, 0x61, 0x6e,
	0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x12, 0x38, 0x0a, 0x0b, 0x61, 0x70, 0x70,
	0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x74, 0x68, 0x65, 0x2e, 0x64, 0x75, 0x6d, 0x6d, 0x79, 0x2e, 0x41, 0x70, 0x70, 0x6c, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x22, 0x71, 0x0a, 0x0b, 0x4a, 0x6f, 0x62, 0x53, 0x6f, 0x66, 0x74, 0x77, 0x61,
	0x72, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x6a, 0x6f, 0x62, 0x5f, 0x73, 0x6f, 0x66, 0x74, 0x77, 0x61,
	0x72, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0f, 0x6a, 0x6f, 0x62,
	0x5f, 0x73, 0x6f, 0x66, 0x74, 0x77, 0x61, 0x72, 0x65, 0x5f, 0x69, 0x64, 0x12, 0x38, 0x0a, 0x0b,
	0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x74, 0x68, 0x65, 0x2e, 0x62, 0x61, 0x73, 0x69, 0x63, 0x2e, 0x41, 0x70,
	0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x61, 0x70, 0x70, 0x6c, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x1b, 0x5a, 0x19, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63,
	0x74, 0x30, 0x31, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6a, 0x6f, 0x62, 0x73, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_jobsearch_jobsearch_proto_rawDescOnce sync.Once
	file_jobsearch_jobsearch_proto_rawDescData = file_jobsearch_jobsearch_proto_rawDesc
)

func file_jobsearch_jobsearch_proto_rawDescGZIP() []byte {
	file_jobsearch_jobsearch_proto_rawDescOnce.Do(func() {
		file_jobsearch_jobsearch_proto_rawDescData = protoimpl.X.CompressGZIP(file_jobsearch_jobsearch_proto_rawDescData)
	})
	return file_jobsearch_jobsearch_proto_rawDescData
}

var file_jobsearch_jobsearch_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_jobsearch_jobsearch_proto_goTypes = []interface{}{
	(*JobCandidate)(nil),      // 0: JobCandidate
	(*JobSoftware)(nil),       // 1: JobSoftware
	(*dummy.Application)(nil), // 2: the.dummy.Application
	(*basic.Application)(nil), // 3: the.basic.Application
}
var file_jobsearch_jobsearch_proto_depIdxs = []int32{
	2, // 0: JobCandidate.application:type_name -> the.dummy.Application
	3, // 1: JobSoftware.application:type_name -> the.basic.Application
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_jobsearch_jobsearch_proto_init() }
func file_jobsearch_jobsearch_proto_init() {
	if File_jobsearch_jobsearch_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_jobsearch_jobsearch_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JobCandidate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jobsearch_jobsearch_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JobSoftware); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_jobsearch_jobsearch_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_jobsearch_jobsearch_proto_goTypes,
		DependencyIndexes: file_jobsearch_jobsearch_proto_depIdxs,
		MessageInfos:      file_jobsearch_jobsearch_proto_msgTypes,
	}.Build()
	File_jobsearch_jobsearch_proto = out.File
	file_jobsearch_jobsearch_proto_rawDesc = nil
	file_jobsearch_jobsearch_proto_goTypes = nil
	file_jobsearch_jobsearch_proto_depIdxs = nil
}
