# https://taskfile.dev

version: '3'

vars:
  version: v2.1.0
  constructs: v10.0.5


env:
  AWS_DEFAULT_REGION: eu-central-1
  CDK_DEFAULT_REGION: eu-central-1
  CDK_DEFAULT_ACCOUNT: 
    sh: aws sts get-caller-identity --query Account --output text

# begin subtasks
includes:
  app:
    taskfile: ./app/Taskfile.yml
    dir: ./app
  infra:
    taskfile: ./infra/Taskfile.yml
    dir: ./infra
# end subtasks    
tasks:
