name: Pull Request Generate Protobuf Go

on:
  push:
    branches:
      - staging
    paths:
      - 'udemy/HandsOngRPC/proto/**.proto'
jobs:
  generate-protobuf-go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          sparse-checkout: udemy/HandsOngRPC/proto
          sparse-checkout-cone-mode: false
      - name: Move files to root
        run: |
          mv udemy/HandsOngRPC/proto/* .
          rm -rf udemy
          ls -lah