name: Pull Request Generate Protobuf Go

on:
  push:
    branches:
      - staging
    paths:
      - 'udemy/HandsOngRPC/proto/**.proto'
jobs:
  # List directory files
  list-files:
    runs-on: ubuntu-latest
    steps:
      - name: List files
        run: ls -la